### ISSUE TITLE
Docs: Where can I use this project?

### ISSUE THREAD

**Issue by ched-dev** [directus-community/schema-builder-kit#1]
I'd love to use this to generate some fields on an existing Data Model and curious where I can use it. Does it work in CLI commands? From a node.js backend? Browser only?

**Comment by ched-dev** [comment]
After playing with the project locally, I can confirm:

- Runs in node.js (as a script or in node application)
- Runs in CLI via an npm script (e.g. see [`npm run blog`](https://github.com/directus-community/schema-builder-kit/blob/main/templates/package.json#L7)) or other custom CLI command to run a node script
- Runs in browser (with transpiler)

**Comment by tiehumobilenow** [comment]
> After playing with the project locally, I can confirm:
> 
> * Runs in node.js (as a script or in node application)
> * Runs in CLI via an npm script (e.g. see [`npm run blog`](https://github.com/directus-community/schema-builder-kit/blob/main/templates/package.json#L7)) or other custom CLI command to run a node script
> * Runs in browser (with transpiler)

Thax!!
